import json


def render(data):
    payload = json.dumps(data, separators=(",", ":"), allow_nan=False)
    html = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SolvX — Bay of Bengal 3D</title>
<style>
html,body,#app{margin:0;width:100%;height:100%;overflow:hidden}body{font-family:Inter,system-ui,sans-serif;background:#dfeaf1;color:#18323b}#app{position:fixed;inset:0}canvas{display:block;width:100%!important;height:100%!important}.ui{position:absolute;z-index:20;background:rgba(242,248,249,.94);border:1px solid rgba(25,73,88,.14);box-shadow:0 12px 36px rgba(27,60,72,.14);backdrop-filter:blur(12px)}#brand{left:15px;top:15px;padding:11px 14px;border-radius:14px}#brand b{font-size:14px;letter-spacing:.2em}#brand small{display:block;margin-top:3px;font-size:8px;color:#667f87}.toolbar{right:15px;top:15px;display:flex;gap:3px;padding:5px;border-radius:14px}.btn{border:0;background:transparent;color:#57737b;border-radius:9px;padding:8px 10px;font-size:9px;cursor:pointer}.btn.active,.btn:hover{background:#d3eaf0;color:#145263}#panel{right:15px;top:76px;width:300px;padding:14px;border-radius:16px}.section{padding:11px 0;border-top:1px solid rgba(25,73,88,.12)}.section:first-child{border-top:0;padding-top:0}.title{font-size:10px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;margin-bottom:8px;color:#496772}.sub,.status{font-size:8px;line-height:1.5;color:#6c848c}.row{display:flex;align-items:center;gap:8px}.row input{width:100%}.value{min-width:48px;text-align:right;font-size:9px;color:#326776}.statusline{display:flex;gap:7px;align-items:center}.dot{width:6px;height:6px;border-radius:50%;background:#3b9654}.dot.busy{background:#c4872d}.dot.error{background:#bf4b43}#legend{left:15px;bottom:15px;width:220px;padding:12px;border-radius:15px}.legend-title{font-size:9px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;margin-bottom:8px}.bar{height:13px;border-radius:999px;background:linear-gradient(90deg,#c7f8f5,#62dbe8,#23b2d9,#147fba,#0c4b87,#071d4e);border:1px solid rgba(0,0,0,.08)}.ticks{display:flex;justify-content:space-between;margin-top:4px;font-size:7px;color:#60777f}.loading{position:absolute;inset:0;display:grid;place-items:center;z-index:50;background:#dfeaf1;text-align:center}.load b{display:block;font-size:24px;letter-spacing:.22em}.load span{display:block;margin-top:7px;font-size:9px;color:#66808a}#hint{left:50%;top:16px;transform:translateX(-50%);padding:7px 10px;border-radius:999px;font-size:8px;color:#637a81;pointer-events:none}#readout{display:none;right:15px;bottom:15px;width:260px;padding:12px;border-radius:15px}.rtitle{font-size:10px;font-weight:800}.rsub{margin-top:3px;font-size:8px;color:#6a838b}.grid{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:8px}.cell{padding:7px;border:1px solid rgba(25,73,88,.12);border-radius:8px;background:rgba(255,255,255,.55)}.cell b{display:block;font-size:7px;color:#678089}.cell span{display:block;margin-top:2px;font-size:10px;font-weight:700;color:#286777}
</style>
<script type="importmap">{"imports":{"three":"https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js","three/addons/":"https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/"}}</script>
</head><body><div id="app"><div id="load" class="loading"><div class="load"><b>SOLVX</b><span id="loadText">BUILDING BAY OF BENGAL</span></div></div><div id="brand" class="ui"><b>SOLVX</b><small>BAY OF BENGAL · GEBCO BATHYMETRY</small></div><div id="hint" class="ui">Drag: orbit · Right drag: pan · Wheel: zoom</div><div id="toolbar" class="ui"><button class="btn active" data-view="3d">3D</button><button class="btn" data-view="top">TOP</button><button class="btn" data-view="profile">PROFILE</button><button class="btn" data-view="under">UNDER</button><button class="btn" id="reset">RESET</button><button class="btn" id="full">FULL</button></div><aside id="panel" class="ui"><div class="section"><div class="title">Ocean base</div><div class="sub">Natural Earth land and coastlines sit above GEBCO seabed relief. Water is rendered as horizontal depth-blended layers instead of a single floating sheet.</div></div><div class="section"><div class="title">Depth exaggeration</div><div class="row"><input id="ex" type="range" min="5" max="100" value="55"><span id="exv" class="value">55×</span></div></div><div class="section"><div class="statusline"><i id="sd" class="dot busy"></i><span id="status" class="status">Loading geometry…</span></div></div></aside><div id="legend" class="ui"><div class="legend-title">Ocean depth</div><div class="bar"></div><div class="ticks"><span>0 m</span><span>-1 km</span><span>-2 km</span><span>-3 km</span><span>-5 km</span></div></div><div id="readout" class="ui"><div class="rtitle">Ocean point</div><div id="coords" class="rsub">—</div><div class="grid"><div class="cell"><b>Depth</b><span id="rdepth">—</span></div><div class="cell"><b>Source</b><span>GEBCO</span></div></div></div></div>
<script type="module">
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const D=__PAYLOAD__;
const app=document.getElementById('app');
const scene=new THREE.Scene(); scene.background=new THREE.Color(0xdfeaf1);
const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,60000);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;app.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.075;controls.screenSpacePanning=true;controls.minDistance=25;controls.maxDistance=22000;controls.mouseButtons.LEFT=THREE.MOUSE.ROTATE;controls.mouseButtons.RIGHT=THREE.MOUSE.PAN;
scene.add(new THREE.HemisphereLight(0xffffff,0x54727b,2.0));const sun=new THREE.DirectionalLight(0xffffff,2.4);sun.position.set(-500,-700,1600);scene.add(sun);
const root=new THREE.Group();scene.add(root);const G={water:new THREE.Group(),seabed:new THREE.Group(),land:new THREE.Group(),coast:new THREE.Group(),eez:new THREE.Group()};Object.values(G).forEach(g=>root.add(g));
let depthScale=55,terrainMesh=null,waterMeshes=[],center={x:0,y:0,size:1000};
const finite=v=>typeof v==='number'&&Number.isFinite(v);const status=(s,k='')=>{document.getElementById('status').textContent=s;document.getElementById('sd').className='dot '+k};
function fit(){const d=Math.max(700,center.size*1.55);camera.position.set(center.x+d*.72,center.y-d*.82,d*.64);controls.target.set(center.x,center.y,-Math.min(100,center.size*.07));camera.far=Math.max(60000,d*12);camera.updateProjectionMatrix();controls.update()}
function buildSeabed(){const t=D.terrain,raw=t.rawDepthKm,nx=t.x.length,ny=t.y.length,pos=new Float32Array(nx*ny*3),col=new Float32Array(nx*ny*3),idx=[];let max=0;for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){const v=raw[j][i];if(finite(v))max=Math.max(max,v)}for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){const k=j*nx+i,o=k*3,v=raw[j][i],q=finite(v)?Math.min(1,v/Math.max(1,max)):0;pos[o]=t.x[i];pos[o+1]=t.y[j];pos[o+2]=finite(v)?-v*depthScale:-2;col[o]=.53-.24*q;col[o+1]=.40-.17*q;col[o+2]=.27-.11*q}for(let j=0;j<ny-1;j++)for(let i=0;i<nx-1;i++){const q=[raw[j][i],raw[j][i+1],raw[j+1][i],raw[j+1][i+1]];if(q.every(finite)){const a=j*nx+i,b=a+1,c=a+nx,d=c+1;idx.push(a,c,b,b,c,d)}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(pos,3));g.setAttribute('color',new THREE.BufferAttribute(col,3));g.setIndex(idx);g.computeVertexNormals();terrainMesh=new THREE.Mesh(g,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.94,side:THREE.DoubleSide}));G.seabed.add(terrainMesh)}
function buildLand(){const polys=[...(D.land?.polygons||[]),...(D.islands?.polygons||[])];const pos=[],idx=[];let off=0;for(const p of polys){if(!p.vertices||!p.triangles)continue;for(const q of p.vertices)pos.push(+q[0],+q[1],8);for(const tri of p.triangles)idx.push(off+tri[0],off+tri[1],off+tri[2]);off+=p.vertices.length}if(!pos.length)return;const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx);const m=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:0x378946,roughness:.88,metalness:0,side:THREE.DoubleSide,polygonOffset:true,polygonOffsetFactor:-2}));G.land.add(m)}
function draw(parts,z,color){const mat=new THREE.LineBasicMaterial({color,depthTest:false});for(const p of parts||[]){if(!p||p.length<2)continue;const g=new THREE.BufferGeometry().setFromPoints(p.map(q=>new THREE.Vector3(+q[0],+q[1],z)));const line=new THREE.Line(g,mat);line.renderOrder=40;G.coast.add(line)}}
function buildEEZ(){const mat=new THREE.LineBasicMaterial({color:0xc79120,depthTest:false});for(const p of D.eez||[]){if(p.length<2)continue;const g=new THREE.BufferGeometry().setFromPoints(p.map(q=>new THREE.Vector3(+q[0],+q[1],10)));const l=new THREE.Line(g,mat);l.renderOrder=50;G.eez.add(l)}}
function buildWater(){const t=D.terrain,raw=t.rawDepthKm,nx=t.x.length,ny=t.y.length;const bands=[{lo:0,hi:.05,c:0xc6f4f2,o:.27},{lo:.05,hi:.2,c:0x54cde1,o:.22},{lo:.2,hi:1,c:0x198fc9,o:.19},{lo:1,hi:3,c:0x0b5ba8,o:.17},{lo:3,hi:6,c:0x173f82,o:.16},{lo:6,hi:12,c:0x091f55,o:.15}];for(const band of bands){const pos=[],idx=[];let vo=0;for(let j=0;j<ny-1;j++)for(let i=0;i<nx-1;i++){const d=[raw[j][i],raw[j][i+1],raw[j+1][i+1],raw[j+1][i]];if(!d.every(finite)||Math.max(...d)<=band.lo)continue;const X=[t.x[i],t.x[i+1],t.x[i+1],t.x[i]],Y=[t.y[j],t.y[j],t.y[j+1],t.y[j+1]],top=d.map(v=>-Math.min(v,band.lo)*depthScale),bot=d.map(v=>-Math.min(v,band.hi)*depthScale);for(let k=0;k<4;k++)pos.push(X[k],Y[k],top[k]);for(let k=0;k<4;k++)pos.push(X[k],Y[k],bot[k]);idx.push(vo,vo+1,vo+2,vo,vo+2,vo+3,vo+4,vo+6,vo+5,vo+4,vo+7,vo+6,vo,vo+4,vo+5,vo,vo+5,vo+1,vo+1,vo+5,vo+6,vo+1,vo+6,vo+2,vo+2,vo+6,vo+7,vo+2,vo+7,vo+3,vo+3,vo+7,vo+4,vo+3,vo+4,vo);vo+=8}if(!pos.length)continue;const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx);const mesh=new THREE.Mesh(g,new THREE.MeshBasicMaterial({color:band.c,transparent:true,opacity:band.o,depthWrite:false,side:THREE.DoubleSide}));mesh.renderOrder=10+bands.indexOf(band);G.water.add(mesh);waterMeshes.push(mesh)}const minX=Math.min(...t.x),maxX=Math.max(...t.x),minY=Math.min(...t.y),maxY=Math.max(...t.y);const surface=new THREE.Mesh(new THREE.PlaneGeometry(maxX-minX,maxY-minY),new THREE.MeshPhysicalMaterial({color:0x159dcc,transparent:true,opacity:.11,roughness:.12,clearcoat:.55,depthWrite:false,side:THREE.DoubleSide}));surface.position.set((minX+maxX)/2,(minY+maxY)/2,2);surface.renderOrder=25;G.water.add(surface)}
function updateDepth(){depthScale=Number(document.getElementById('ex').value);document.getElementById('exv').textContent=depthScale+'×';if(terrainMesh){const a=terrainMesh.geometry.attributes.position,raw=D.terrain.rawDepthKm,nx=D.terrain.x.length;for(let j=0;j<D.terrain.y.length;j++)for(let i=0;i<nx;i++){const v=raw[j][i];a.setZ(j*nx+i,finite(v)?-v*depthScale:-2)}a.needsUpdate=true;terrainMesh.geometry.computeVertexNormals()}}
function view(v){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));const d=Math.max(700,center.size*1.55);if(v==='top')camera.position.set(center.x,center.y,d*.95);else if(v==='profile')camera.position.set(center.x+d*.78,center.y,d*.16);else if(v==='under')camera.position.set(center.x+d*.45,center.y-d*.45,-d*.28);else return fit();controls.target.set(center.x,center.y,v==='top'?0:-120);controls.update()}
async function main(){try{status('Reading supplied geometry…','busy');const t=D.terrain;const minX=Math.min(...t.x),maxX=Math.max(...t.x),minY=Math.min(...t.y),maxY=Math.max(...t.y);center={x:(minX+maxX)/2,y:(minY+maxY)/2,size:Math.max(maxX-minX,maxY-minY)};buildSeabed();status('Building green land…','busy');buildLand();status('Building horizontal water strata…','busy');buildWater();draw(D.coast,11,0x0b6372);draw(D.landBoundary,11.5,0x0b6372);draw(D.islandCoast,12,0x0b6372);buildEEZ();fit();document.getElementById('load').remove();status('3D ocean ready')}catch(e){console.error(e);document.getElementById('loadText').textContent='FAILED — OPEN CONSOLE';status('Renderer failed: '+e.message,'error')}}
document.getElementById('ex').addEventListener('input',updateDepth);document.getElementById('reset').addEventListener('click',fit);document.getElementById('full').addEventListener('click',()=>document.documentElement.requestFullscreen?.());for(const b of document.querySelectorAll('[data-view]'))b.addEventListener('click',()=>view(b.dataset.view));addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});(function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera)})();main();
</script></body></html>'''
    return html.replace('__PAYLOAD__', payload)
